name: Build WebGL Version
on: [ push ]
jobs:
  build-game:
    runs-on: ubuntu-latest
    steps:
      - name: Set up butler
        uses: jdno/setup-butler@v1
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        id: unityBuild
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
      - name: Publish game to itch.io
        run: |
          butler push build tobiusthegrand/shop-sim-with-gathering-pets:webgl --userversion ${{ steps.unityBuild.outputs.buildVersion }}
        env:
          BUTLER_API_KEY: ${{ secrets.ITCHIO_API_KEY }}